# Generated by Django 2.2.28 on 2024-11-17 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lieu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('capacite_max', models.PositiveIntegerField()),
                ('connections', models.ManyToManyField(blank=True, related_name='_lieu_connections_+', to='station.Lieu')),
            ],
        ),
        migrations.CreateModel(
            name='Habitant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('etat', models.CharField(choices=[('actif', 'Actif'), ('repos', 'Repos'), ('fatigué', 'Fatigué'), ('affamé', 'Affamé')], default='actif', max_length=50)),
                ('lieu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='habitants', to='station.Lieu')),
            ],
        ),
    ]
