# Generated by Django 2.2.28 on 2024-11-18 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0002_auto_20241118_0417'),
    ]

    operations = [
        migrations.AddField(
            model_name='lieu',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos_lieux/'),
        ),
    ]
